menu:
  归档: /archives
  关于: /about
  订阅: /atom.xml

widgets:
- tagcloud
- category

favicon: favicon-lightbulb-o.ico

excerpt_link: Read More ›

twitter:
  username:
  show_replies: false
  tweet_count: 5

google_analytics:
